### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by gokaybiz** [srbill1996/CreadorNetflixSelenium#2]
[+]Buscando y escribiendo en email
Traceback (most recent call last):
  File "netflix_paypal.py", line 173, in <module>
    botCrear = NetflixBot().crear_cuenta(datos)
  File "netflix_paypal.py", line 108, in crear_cuenta
    nv.completarFormulario(loginNetflix)

**Comment by hwpoison** [comment]
It is an old code, but if you could better specify the error maybe it could help you

**Comment by gokaybiz** [comment]
Paypal throws declined card error xD
